version: '3'
services:
  api:
    
  black-box:
    build: ./tests/black-box
    environment:
      - API_URL=http://api
      - TEAMCITY_PROJECT_NAME=logging-api
      - http_proxy=http://zap:8090
      - https_proxy=http://zap:8090
    volumes:
      - ./zap/session:/reports